"""
Scan videos/raw/**/*.mp4 and generate:
  streaming/mediamtx.yml   — MediaMTX path declarations
  streaming/streams.json   — {stream_id: absolute_path} manifest
"""
import json
from collections import defaultdict
from pathlib import Path

RAW = Path(__file__).parent / "videos" / "raw"
OUT_DIR = Path(__file__).parent / "streaming"
OUT_DIR.mkdir(exist_ok=True)

videos = sorted(RAW.rglob("*.mp4"))

folder_count = defaultdict(int)
streams = {}

for v in videos:
    folder = v.parent.name
    idx = folder_count[folder]
    folder_count[folder] += 1
    stream_id = folder if idx == 0 and folder_count[folder] == 1 else f"{folder}_{idx}"
    streams[stream_id] = str(v)

# Re-pass to fix single-video folders that got no suffix
folder_count2 = defaultdict(int)
streams2 = {}
folder_totals = defaultdict(int)
for v in videos:
    folder_totals[v.parent.name] += 1

for v in videos:
    folder = v.parent.name
    idx = folder_count2[folder]
    folder_count2[folder] += 1
    if folder_totals[folder] == 1:
        stream_id = folder
    else:
        stream_id = f"{folder}_{idx}"
    # Store path relative to videos/raw so containers can prefix their own mount point
    streams2[stream_id] = str(v.relative_to(RAW))

# Write streams.json
streams_path = OUT_DIR / "streams.json"
streams_path.write_text(json.dumps(streams2, indent=2))
print(f"Written {streams_path}  ({len(streams2)} streams)")

# Write mediamtx.yml — all_others catch-all accepts any publisher path
mediamtx_config = """# Auto-generated by generate_mediamtx_config.py
rtspAddress: :8554
rtmpAddress: :1935
hlsAddress: :8888
apiAddress: :9997
api: yes

pathDefaults:
  source: publisher

paths:
  all_others:
"""
mediamtx_path = OUT_DIR / "mediamtx.yml"
mediamtx_path.write_text(mediamtx_config)
print(f"Written {mediamtx_path}")

print("\nStreams:")
for sid, path in streams2.items():
    print(f"  {sid:30s}  {Path(path).name}")
