services:

  mediamtx:
    image: bluenviron/mediamtx:latest
    command: ["/mediamtx.yml"]
    ports:
      - "8554:8554"   # RTSP
      - "8888:8888"   # HLS
      - "9997:9997"   # API
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
    restart: unless-stopped

  publisher:
    build: ./publisher
    depends_on:
      - mediamtx
    environment:
      MEDIAMTX_HOST: mediamtx
      MEDIAMTX_PORT: "8554"
      STREAMS_JSON: /streams.json
    volumes:
      - ../videos/raw:/videos:ro
      - ./streams.json:/streams.json:ro
    restart: unless-stopped

  frontend:
    build: ./frontend
    depends_on:
      - analyzer
    ports:
      - "3000:80"
    restart: unless-stopped

  analyzer:
    build: ./analyzer
    depends_on:
      - mediamtx
    ports:
      - "8080:8080"
    environment:
      MEDIAMTX_HOST: mediamtx
      MEDIAMTX_PORT: "8554"
      STREAMS_JSON: /streams.json
      SAMPLE_FRAMES: "11"
      SAMPLE_INTERVAL: "0"
      STREAMS_LIMIT: "3"
      ENABLE_SSIM: "false"     # set to "true" to enable SSIM (slower)
      HTTP_PORT: "8080"
      FEED_MAX_ITEMS: "500"
    volumes:
      - ./streams.json:/streams.json:ro
    restart: unless-stopped
